version: 0.2
phases:
  install:
    commands:
      npm install
  build:
    commands:
      npm run build
artifacts:
  type: zip
  files:
    - .npmrc
    - .env.production
    - tsconfig.paths.json
    - tsconfig-paths-bootstrap.js
    - package.json
    - package-lock.json
    - 'dist/**/*'